@echo off
echo Restarting Backend Server...
cd /d "e:\copy\EntraDigimart-test\digiMart-backend"
echo Stopping any existing server...
taskkill /f /im node.exe >nul 2>&1
echo Starting server...
node server.js